title: ImageBox
description: Display an image in a responsive imagebox without jQuery.
logo: images/logo.png
theme: jekyll-theme-minimal
show_downloads: true
github:
  zip_url: https://github.com/tobiasroeder/ImageBox/zipball/master
  tar_url: https://github.com/tobiasroeder/ImageBox/tarball/master
